spring:
  application:
    name: TgBotDocker

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 56cbtm1b
    url: jdbc:postgresql://localhost:5432/NewsBD


  jpa:
    hibernate:
      ddl-auto: create


bot:
  token: 7775107175:AAEY0DUBlIbcyutM4nQY9K1-AD7ciXYiPxc
  name: tgBot0912_bot